version: "3.8"
services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    restart: always
  service-alpha:
    build: ./service-alpha
    ports:
      - "7080:8080"
    restart: always
    depends_on:
      - service-bravo
      - localstack
  service-bravo:
    build: ./service-bravo
    ports:
      - "7081:8080"
    restart: always
    depends_on:
      - service-bravo-database
  service-bravo-database:
    image: postgres:16.1-bullseye
    ports:
      - "7432:5432"
    volumes:
      - service-bravo-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bravo
    restart: always
volumes:
  service-bravo-database:
